/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaLED */

#ifndef _Included_JavaLED
#define _Included_JavaLED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaLED
 * Method:    initLED
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaLED_initLED
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaLED
 * Method:    setLED
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaLED_setLED
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
