/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaButton */

#ifndef _Included_JavaButton
#define _Included_JavaButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaButton
 * Method:    initButton
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaButton_initButton
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaButton
 * Method:    readButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaButton_readButton
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
